---

- hosts: web
  name: My Web Group Apache Deployment
  sudo: yes 
  tasks: 
  - name: Install Apache2 Packages
    apt: name=apache2 state=present

  - name: Bring up Apache Service 
    service: name=apache2 state=started

  - name: Deploy my custom Index Web page
    copy: src=files/index.html  dest=/var/www/html/index.html



- hosts: db
  name: My DB Group Apache Deployment
  sudo: yes 
  tasks: 
  - name: Install Apache2 Packages
    apt: name=apache2 state=present
